version: '3.11'

services:
  excel-analytics-app-v4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: excel-analytics-app-v4
    ports:
      - "5000:5000"  
    environment:
      - ONLYOFFICE_SERVER_URL=https://ai-ods-demo.azurewebsites.net
      - ONLYOFFICE_CALLBACK_URL=http://localhost:5000/onlyoffice/callback
      - FLASK_ENV=development  
      - FLASK_DEBUG=false  # Set to False for production
    privileged: true
    volumes:
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads
      - ./documents:/app/documents
      - ./logs:/app/logs
    restart: unless-stopped
